# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Home Assistant builder
        uses: home-assistant/builder@2022.07.0
        with:        
          args: |
            --test \
            --armv7 \
            --docker-hub user-name-or-space-name

