name: Builder

env:
  BUILD_ARGS: " "

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.0.2
        
      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

  build:
    runs-on: ubuntu-latest
    name: Build calibre_web_plus armv7 add-on
    strategy:
      matrix:
        addon: ["calibre_web_plus"]
        arch: ["armv7"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./calibre_web_plus"
          
      - name: Build calibre_web_plus add-on
        uses: home-assistant/builder@2022.07.0
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --armv7 \
            --target /data/calibre_web_plus \
            --image "${{ steps.check.outputs.image }}" \
            --docker-hub "${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}" \
            --docker-user "${{ secrets.DOCKER_HUB_USERNAME }}" \
            --docker-password "${{ secrets.DOCKER_HUB_TOKEN }}" \
            --addon
